version: "3.7"
services:
  minharinha1:
    image: minha-rinha-app
    hostname: minharinha1
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl 127.0.0.1:9999"]
      interval: 3s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '2GB'
    environment:
      RINHA_DB_ADDRESS: postgres
      RINHA_DB: rinhadb
      RINHA_DB_USER: rinha
      RINHA_DB_PASSWORD: rinha123
      SPRING_PORT: 9999
      RINHA_DB_MAX_POOL: 20
    ports:
      - 9999:9999
    networks:
      - rinha-network
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinhadb
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '1GB'
    networks:
      - rinha-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
networks:
  rinha-network: