server:
  port: ${SPRING_PORT:9999}

spring:
  mvc:
    logResolvedException: false
  datasource:
    url: jdbc:postgresql://${RINHA_DB_ADDRESS:localhost}:5432/${RINHA_DB:rinhadb}
    username: ${RINHA_DB_USER:rinha}
    password: ${RINHA_DB_PASSWORD:rinha123}
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      debug: true
      testOnBorrow: true
      testOnReturn: true
      connectionTestQuery: SELECT 1
      connectionTimeout: 3000
      maxLifetime: 1800000
      leakDetectionThreshold: 300000
#      minimumIdle: 10
      validationTimeout: 2500
#      idleTimeout: 600000
      autoCommit: true
      maximumPoolSize: ${RINHA_DB_MAX_POOL:16}
      poolName: RinhaTest
      transactionIsolation: TRANSACTION_READ_COMMITTED
  data:
    jdbc:
      schema: PUBLIC

#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: debug
#        jdbc:
#          core:
#            JdbcTemplate: DEBUG
#            StatementCreatorUtils: TRACE